// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema3.prisma",
  migrations: {
    path: "prisma/migrations_3",
  },
  datasource: {
    url: env("DATABASE_URL_3"),
  },
});
